recognition:
  service:
    sightEnabled: false
    webcams:
      - http://11.0.0.100:8080/?action=snapshot

sighthound:
  client:
    recognizeUrl: https://prod.sighthoundapi.com/v1/recognition?objectType=vehicle,licenseplate
    detectUrl: https://prod.sighthoundapi.com/v1/detections?type=face,person&faceOption=gender,age,emotion,pose
    accessToken: nWE5seUaAixq2VJFshi80m6hFDS4LnU6JZVc