local:
  sightEnabled: false
  webcams:
    - http://192.168.1.104:8080/photoaf.jpg
    - http://192.168.1.103:8080/photoaf.jpg

sighthound:
  client:
    recognizeUrl: https://prod.sighthoundapi.com/v1/recognition?objectType=vehicle,licenseplate
    detectUrl: https://prod.sighthoundapi.com/v1/detections?type=face,person&faceOption=gender,age,emotion,pose
    accessToken: nWE5seUaAixq2VJFshi80m6hFDS4LnU6JZVc